#include <R_ext/RS.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>
#include <Rinternals.h>

/* .Fortran calls */
extern void F77_NAME(lddpsurvival)(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void F77_NAME(hpd)(void *, void *, void *, void *, void *);

/* Rcpp module boot symbols generated by rstantools */
extern SEXP _rcpp_module_boot_stan_fit4exponential_imputation_mod(void);
extern SEXP _rcpp_module_boot_stan_fit4lognormal_imputation_mod(void);
extern SEXP _rcpp_module_boot_stan_fit4weibull_imputation_mod(void);

/* 'lddpsurvival' and 'hpd' are vendored from DPpackage (Jara et al.) */
static const R_FortranMethodDef FortranEntries[] = {
    {"lddpsurvival", (DL_FUNC) &F77_NAME(lddpsurvival), 65},
    {"hpd",          (DL_FUNC) &F77_NAME(hpd),           5},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4exponential_imputation_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4exponential_imputation_mod, 0},
    {"_rcpp_module_boot_stan_fit4lognormal_imputation_mod",   (DL_FUNC) &_rcpp_module_boot_stan_fit4lognormal_imputation_mod,   0},
    {"_rcpp_module_boot_stan_fit4weibull_imputation_mod",     (DL_FUNC) &_rcpp_module_boot_stan_fit4weibull_imputation_mod,     0},
    {NULL, NULL, 0}
};

#ifdef _WIN32
# include <fcntl.h>
#endif

void R_init_bird(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, FortranEntries, NULL);
    R_useDynamicSymbols(dll, FALSE);

#ifdef _WIN32
    /* gfortran initialisation sets these to _O_BINARY */
    setmode(1, _O_TEXT); /* stdout */
    setmode(2, _O_TEXT); /* stderr */
#endif
}
