// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_lognormal_imputation_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 50> locations_array__ =
  {" (found before start of program)",
  " (in 'lognormal_imputation', line 21, column 2 to column 10)",
  " (in 'lognormal_imputation', line 22, column 2 to column 25)",
  " (in 'lognormal_imputation', line 38, column 2 to column 36)",
  " (in 'lognormal_imputation', line 41, column 2 to column 23)",
  " (in 'lognormal_imputation', line 42, column 2 to column 25)",
  " (in 'lognormal_imputation', line 45, column 2 to column 55)",
  " (in 'lognormal_imputation', line 46, column 2 to column 58)",
  " (in 'lognormal_imputation', line 47, column 2 to column 50)",
  " (in 'lognormal_imputation', line 51, column 4 to column 53)",
  " (in 'lognormal_imputation', line 50, column 21 to line 52, column 3)",
  " (in 'lognormal_imputation', line 50, column 2 to line 52, column 3)",
  " (in 'lognormal_imputation', line 54, column 4 to column 56)",
  " (in 'lognormal_imputation', line 53, column 22 to line 55, column 3)",
  " (in 'lognormal_imputation', line 53, column 2 to line 55, column 3)",
  " (in 'lognormal_imputation', line 61, column 4 to column 31)",
  " (in 'lognormal_imputation', line 62, column 4 to column 37)",
  " (in 'lognormal_imputation', line 65, column 4 to column 52)",
  " (in 'lognormal_imputation', line 66, column 23 to column 37)",
  " (in 'lognormal_imputation', line 66, column 4 to column 37)",
  " (in 'lognormal_imputation', line 67, column 23 to column 37)",
  " (in 'lognormal_imputation', line 67, column 4 to column 37)",
  " (in 'lognormal_imputation', line 70, column 4 to column 37)",
  " (in 'lognormal_imputation', line 71, column 16 to column 26)",
  " (in 'lognormal_imputation', line 71, column 4 to column 26)",
  " (in 'lognormal_imputation', line 72, column 16 to column 29)",
  " (in 'lognormal_imputation', line 72, column 4 to column 29)",
  " (in 'lognormal_imputation', line 74, column 4 to column 24)",
  " (in 'lognormal_imputation', line 75, column 4 to column 40)",
  " (in 'lognormal_imputation', line 76, column 4 to column 38)",
  " (in 'lognormal_imputation', line 79, column 34 to column 75)",
  " (in 'lognormal_imputation', line 79, column 4 to column 75)",
  " (in 'lognormal_imputation', line 58, column 22 to line 80, column 3)",
  " (in 'lognormal_imputation', line 58, column 2 to line 80, column 3)",
  " (in 'lognormal_imputation', line 26, column 2 to column 42)",
  " (in 'lognormal_imputation', line 27, column 2 to column 36)",
  " (in 'lognormal_imputation', line 30, column 2 to column 46)",
  " (in 'lognormal_imputation', line 33, column 2 to column 48)",
  " (in 'lognormal_imputation', line 5, column 2 to column 21)",
  " (in 'lognormal_imputation', line 6, column 2 to column 22)",
  " (in 'lognormal_imputation', line 9, column 18 to column 23)",
  " (in 'lognormal_imputation', line 9, column 2 to column 31)",
  " (in 'lognormal_imputation', line 10, column 18 to column 24)",
  " (in 'lognormal_imputation', line 10, column 2 to column 33)",
  " (in 'lognormal_imputation', line 14, column 2 to column 21)",
  " (in 'lognormal_imputation', line 15, column 2 to column 28)",
  " (in 'lognormal_imputation', line 18, column 2 to column 31)",
  " (in 'lognormal_imputation', line 38, column 18 to column 24)",
  " (in 'lognormal_imputation', line 41, column 9 to column 14)",
  " (in 'lognormal_imputation', line 42, column 9 to column 15)"};
#include <stan_meta_header.hpp>
class model_lognormal_imputation final : public model_base_crtp<model_lognormal_imputation> {
private:
  int n_obs;
  int n_cens;
  Eigen::Matrix<double,-1,1> t_obs_data__;
  Eigen::Matrix<double,-1,1> t_cens_data__;
  double mu_prior_mean;
  double mu_prior_sd;
  double sigma_prior_sd;
  Eigen::Map<Eigen::Matrix<double,-1,1>> t_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> t_cens{nullptr, 0};
public:
  ~model_lognormal_imputation() {}
  model_lognormal_imputation(stan::io::var_context& context__, unsigned int
                             random_seed__ = 0, std::ostream*
                             pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_lognormal_imputation_namespace::model_lognormal_imputation";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 38;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{});
      n_obs = std::numeric_limits<int>::min();
      current_statement__ = 38;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "n_obs", n_obs, 0);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "n_cens", "int",
        std::vector<size_t>{});
      n_cens = std::numeric_limits<int>::min();
      current_statement__ = 39;
      n_cens = context__.vals_i("n_cens")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "n_cens", n_cens, 0);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("t_obs", "n_obs", n_obs);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "t_obs", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      t_obs_data__ = Eigen::Matrix<double,-1,1>::Constant(n_obs,
                       std::numeric_limits<double>::quiet_NaN());
      new (&t_obs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(t_obs_data__.data(), n_obs);
      {
        std::vector<local_scalar_t__> t_obs_flat__;
        current_statement__ = 41;
        t_obs_flat__ = context__.vals_r("t_obs");
        current_statement__ = 41;
        pos__ = 1;
        current_statement__ = 41;
        for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
          current_statement__ = 41;
          stan::model::assign(t_obs, t_obs_flat__[(pos__ - 1)],
            "assigning variable t_obs", stan::model::index_uni(sym1__));
          current_statement__ = 41;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "t_obs", t_obs, 0);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("t_cens", "n_cens", n_cens);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "t_cens", "double",
        std::vector<size_t>{static_cast<size_t>(n_cens)});
      t_cens_data__ = Eigen::Matrix<double,-1,1>::Constant(n_cens,
                        std::numeric_limits<double>::quiet_NaN());
      new (&t_cens)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(t_cens_data__.data(), n_cens);
      {
        std::vector<local_scalar_t__> t_cens_flat__;
        current_statement__ = 43;
        t_cens_flat__ = context__.vals_r("t_cens");
        current_statement__ = 43;
        pos__ = 1;
        current_statement__ = 43;
        for (int sym1__ = 1; sym1__ <= n_cens; ++sym1__) {
          current_statement__ = 43;
          stan::model::assign(t_cens, t_cens_flat__[(pos__ - 1)],
            "assigning variable t_cens", stan::model::index_uni(sym1__));
          current_statement__ = 43;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "t_cens", t_cens, 0);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "mu_prior_mean",
        "double", std::vector<size_t>{});
      mu_prior_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 44;
      mu_prior_mean = context__.vals_r("mu_prior_mean")[(1 - 1)];
      current_statement__ = 45;
      context__.validate_dims("data initialization", "mu_prior_sd", "double",
        std::vector<size_t>{});
      mu_prior_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 45;
      mu_prior_sd = context__.vals_r("mu_prior_sd")[(1 - 1)];
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "mu_prior_sd",
        mu_prior_sd, 0);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "sigma_prior_sd",
        "double", std::vector<size_t>{});
      sigma_prior_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 46;
      sigma_prior_sd = context__.vals_r("sigma_prior_sd")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "sigma_prior_sd",
        sigma_prior_sd, 0);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("t_imputed", "n_cens", n_cens);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("ll_obs", "n_obs", n_obs);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("ll_cens", "n_cens", n_cens);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_lognormal_imputation";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_lognormal_imputation_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(1e-6, lp__);
      {
        current_statement__ = 34;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, mu_prior_mean,
                         mu_prior_sd));
        current_statement__ = 35;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma, 0,
                         sigma_prior_sd));
        current_statement__ = 36;
        lp_accum__.add(stan::math::lognormal_lpdf<false>(t_obs, mu, sigma));
        current_statement__ = 37;
        lp_accum__.add(stan::math::lognormal_lccdf(t_cens, mu, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_lognormal_imputation_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      mu = in__.template read<local_scalar_t__>();
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(1e-6, lp__);
      out__.write(mu);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> t_imputed =
        Eigen::Matrix<double,-1,1>::Constant(n_cens,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> ll_obs =
        Eigen::Matrix<double,-1,1>::Constant(n_obs,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> ll_cens =
        Eigen::Matrix<double,-1,1>::Constant(n_cens,
          std::numeric_limits<double>::quiet_NaN());
      double log_lik_obs = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      log_lik_obs = stan::math::lognormal_lpdf<false>(t_obs, mu, sigma);
      double log_lik_cens = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      log_lik_cens = stan::math::lognormal_lccdf(t_cens, mu, sigma);
      double log_lik_total = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      log_lik_total = (log_lik_obs + log_lik_cens);
      current_statement__ = 11;
      for (int i = 1; i <= n_obs; ++i) {
        current_statement__ = 9;
        stan::model::assign(ll_obs,
          stan::math::lognormal_lpdf<false>(
            stan::model::rvalue(t_obs, "t_obs", stan::model::index_uni(i)),
            mu, sigma), "assigning variable ll_obs",
          stan::model::index_uni(i));
      }
      current_statement__ = 14;
      for (int i = 1; i <= n_cens; ++i) {
        current_statement__ = 12;
        stan::model::assign(ll_cens,
          stan::math::lognormal_lccdf(
            stan::model::rvalue(t_cens, "t_cens", stan::model::index_uni(i)),
            mu, sigma), "assigning variable ll_cens",
          stan::model::index_uni(i));
      }
      current_statement__ = 33;
      for (int i = 1; i <= n_cens; ++i) {
        double u = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 15;
        u = stan::math::uniform_rng(0, 1, base_rng__);
        double log_t_cens = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 16;
        log_t_cens = stan::math::log(
                       stan::model::rvalue(t_cens, "t_cens",
                         stan::model::index_uni(i)));
        double Phi_c = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 17;
        Phi_c = stan::math::normal_cdf(log_t_cens, mu, sigma);
        current_statement__ = 19;
        if (stan::math::logical_lt(Phi_c, 1e-10)) {
          current_statement__ = 18;
          Phi_c = 1e-10;
        }
        current_statement__ = 21;
        if (stan::math::logical_gt(Phi_c, 0.999)) {
          current_statement__ = 20;
          Phi_c = 0.999;
        }
        double p = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 22;
        p = (Phi_c + (u * (1 - Phi_c)));
        current_statement__ = 24;
        if (stan::math::logical_lte(p, 0)) {
          current_statement__ = 23;
          p = 1e-10;
        }
        current_statement__ = 26;
        if (stan::math::logical_gte(p, 1)) {
          current_statement__ = 25;
          p = 0.999999;
        }
        double z = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 27;
        z = stan::math::inv_Phi(p);
        double log_t_imputed = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 28;
        log_t_imputed = (mu + (sigma * z));
        current_statement__ = 29;
        stan::model::assign(t_imputed, stan::math::exp(log_t_imputed),
          "assigning variable t_imputed", stan::model::index_uni(i));
        current_statement__ = 31;
        if (stan::math::logical_lt(
              stan::model::rvalue(t_imputed, "t_imputed",
                stan::model::index_uni(i)),
              stan::model::rvalue(t_cens, "t_cens", stan::model::index_uni(i)))) {
          current_statement__ = 30;
          stan::model::assign(t_imputed,
            (stan::model::rvalue(t_cens, "t_cens", stan::model::index_uni(i))
            * (1.0 + 1e-12)), "assigning variable t_imputed",
            stan::model::index_uni(i));
        }
      }
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "t_imputed", t_imputed,
        0);
      out__.write(t_imputed);
      out__.write(ll_obs);
      out__.write(ll_cens);
      out__.write(log_lik_obs);
      out__.write(log_lik_cens);
      out__.write(log_lik_total);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.read<local_scalar_t__>();
      out__.write(mu);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(1e-6, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write(mu);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(1e-6, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "sigma"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"t_imputed", "ll_obs", "ll_cens", "log_lik_obs", "log_lik_cens",
             "log_lik_total"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n_cens)},
             std::vector<size_t>{static_cast<size_t>(n_obs)},
             std::vector<size_t>{static_cast<size_t>(n_cens)},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_cens; ++sym1__) {
        param_names__.emplace_back(std::string() + "t_imputed" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "ll_obs" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_cens; ++sym1__) {
        param_names__.emplace_back(std::string() + "ll_cens" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "log_lik_obs");
      param_names__.emplace_back(std::string() + "log_lik_cens");
      param_names__.emplace_back(std::string() + "log_lik_total");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_cens; ++sym1__) {
        param_names__.emplace_back(std::string() + "t_imputed" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "ll_obs" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_cens; ++sym1__) {
        param_names__.emplace_back(std::string() + "ll_cens" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "log_lik_obs");
      param_names__.emplace_back(std::string() + "log_lik_cens");
      param_names__.emplace_back(std::string() + "log_lik_total");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"t_imputed\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_cens) + "},\"block\":\"generated_quantities\"},{\"name\":\"ll_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_obs) + "},\"block\":\"generated_quantities\"},{\"name\":\"ll_cens\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_cens) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik_obs\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik_cens\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik_total\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"t_imputed\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_cens) + "},\"block\":\"generated_quantities\"},{\"name\":\"ll_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_obs) + "},\"block\":\"generated_quantities\"},{\"name\":\"ll_cens\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_cens) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik_obs\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik_cens\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik_total\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities *
      ((((((n_cens + n_obs) + n_cens) + 1) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities *
      ((((((n_cens + n_obs) + n_cens) + 1) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_lognormal_imputation_namespace::model_lognormal_imputation;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_lognormal_imputation_namespace::profiles__;
}
#endif
#endif
